name: 'Moovr'
main: us.zethr.us.moovr.Moovr
version: '${project.version}'
api-version: '1.20'
description: We like to moove it.
author: Zethrus
dev-url: 'https://github.com/zethrus/Moovr'
commands:
  moovr:
    description: Moovr command
    usage: /moovr
  moovrsetspeed:
    description: Sets the Moovr speed
    usage: /moovrsetspeed <amount>
    permission: moovr.setspeed
  moovrtoggle:
    description: Toggles the Moovr functionality on/off for the player
    permission: moovr.toggle
  moovrreload:
    description: Reloads the config.yml
    permission: moovr.reload

permissions:
  moovr.reload:
    description: Allows the player to reload the Moovr configuration
  moovr.setspeed:
    description: Allows the player to set the Moovr speed
  moovr.toggle:
    description: Allows the player to toggle the Moovr functionality for themselves
  moovr.use:
    description: Allows the player to use a Moovr block