name: 'Moovr'
main: us.zethr.us.moovr.Moovr
version: '1.0'
api-version: '1.20'
description: We like to moove it.
author: Zethrus
dev-url: 'https://github.com/zethrus/Moovr'
commands:
  moovr reload:
    description: Reloads the Moovr configuration
    permission: moovr.reload
  moovr setspeed:
    description: Sets the Moovr speed
    usage: /moovr setspeed <amount>
    permission: moovr.setspeed
  moovr toggle:
    description: Toggles the Moovr functionality on/off for the player
    permission: moovr.toggle

permissions:
  moovr.reload:
    description: Allows the player to reload the Moovr configuration
  moovr.setspeed:
    description: Allows the player to set the Moovr speed
  moovr.toggle:
    description: Allows the player to toggle the Moovr functionality