name: 'Moovr'
main: us.zethr.us.moovr.Moovr
version: '1.0'
api-version: '1.20'
description: We like to moove it.
author: Zethrus
dev-url: 'https://github.com/zethrus/Moovr'
commands:
  moovr:
    description: Reloads the Moovr plugin
    usage: /moovr reload
    permission: moovr.reload
permissions:
    moovr.use:
        description: Allows a user to use a Moovr pad
        default: op
    moovr.reload:
        description: Allows a user to reload Moovr config.yml
        default: op