name: 'Moovr'
main: us.zethr.us.moovr.Moovr
version: '1.0'
api-version: '1.20'
description: We like to moove it.
author: Zethrus
dev-url: 'https://github.com/zethrus/Moovr'
commands:
  moovrreload:
    description: Reload Moovr configuration
    usage: /moovrreload
    permission: moovr.reload
  moovrsetspeed:
    description: Set the Moovr speed
    usage: /moovrsetspeed <amount>
    permission: moovr.setspeed

permissions:
  moovr.reload:
    description: Allows the player to reload Moovr configuration
    default: op
  moovr.setspeed:
    description: Allows the player to set the Moovr speed
    default: op