name: 'Moovr'
main: us.zethr.us.moovr.Moovr
version: '1.0'
api-version: '1.20'
description: We like to moove it.
author: Zethrus
dev-url: 'https://github.com/zethrus/Moovr'
commands:
  moovr:
    description: Moovr plugin command
    usage: /moovr <reload|setspeed>
    permission: moovr.use
    aliases: [mvr]

permissions:
  moovr.reload:
    description: Allows the player to reload Moovr configuration
    default: op
  moovr.setspeed:
    description: Allows the player to set the Moovr speed
    default: op